create database bookdb;

use bookdb;

create table TBL_BOOKS(
B_CODE	VARCHAR(6)	NOT NULL	PRIMARY KEY,
B_NAME	VARCHAR(125)	NOT NULL,	
B_AUTHER	VARCHAR(125)	NOT NULL,	
B_COMP	VARCHAR(125),		
B_YEAR	INT	NOT NULL,	
B_IPRICE	INT,		
B_RPRICE	INT	NOT NULL	
);

create table TBL_USERS(
U_CODE	VARCHAR(6)	NOT NULL	PRIMARY KEY,
U_NAME	VARCHAR(125)	NOT NULL,	
U_TEL	VARCHAR(125),		
U_ADDR	VARCHAR(125)		
);


create table TBL_RENT_BOOK(
RENT_SEQ	BIGINT	AUTO_INCREMENT	PRIMARY KEY,
RENT_DATE	VARCHAR(30)	NOT NULL,	
RENT_RETURN_DATE	VARCHAR(10)	NOT NULL,	
RENT_BCODE	VARCHAR(6),		
RENT_UCODE	VARCHAR(6)	NOT NULL	,
RENT_RETUR_YN	VARCHAR(1),		
RENT_POINT	INT	NOT NULL	

);

ALTER TABLE TBL_RENT_BOOK ADD CONSTRAINT FK_BOOKS
FOREIGN KEY (RENT_BCODE) REFERENCES TBL_BOOKS(B_CODE);

ALTER TABLE TBL_RENT_BOOK ADD CONSTRAINT FK_USERS
FOREIGN KEY (RENT_UCODE) REFERENCES TBL_USERS(U_CODE);


DESC TBL_RENT_BOOK;
DESC TBL_books;
DESC TBL_users;
COMMIT;
SELECT * FROM TBL_BOOKS;
insert into TBL_BOOKS(B_CODE,B_NAME,B_AUTHER,B_COMP,B_YEAR,B_IPRICE,B_RPRICE) VALUE('1','제목1','작가1','COMP',2023,1000,500);

SELECT * FROM TBL_BOOKS ORDER BY B_CODE;